[package]
name = "hass-mqtt-autodiscovery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rumqttc = "0.23"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
assert-json-diff = "2.0"
testcontainers = "0.15"
tokio = "1.25"